name: Format, test and preview

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  format:
    name: Lint and format project
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v2

      - name: 'Setup node'
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Lint'
        run: npm run lint

      - name: 'Format'
        run: npm run prettier
